### ISSUE TITLE
TYPO3 8 LTS support

### ISSUE THREAD

**Issue by macjohnny** [svewap/ws_less#21]
Hi

Would it be possible to make this extension TYPO3 8 LTS compatible?

Cheers

**Comment by svewap** [comment]
Hi! The problem is the free time. I can not say when I will be able to do this.

**Comment by oliverschloebe** [comment]
> Hi! The problem is the free time. I can not say when I will be able to do this.

Would it be possible to adopt the extension and keep it updated? I mean, one could just fork the extension, but I'd like to keep the current extension key `ws_less` without flooding the TYPO3 extension repo with forked extensions. ✌️

**Comment by svewap** [comment]
If you want, you can work on this repository, make pull requests or I can add you to as collaborator. Just feel free to contact me ;-)

**Comment by oliverschloebe** [comment]
Adding me as a collaborator would be much appreciated, thank you!

However, my plans are to **drop support for TYPO3 <= 7** (as support has been dropped anyways) and make the extension compatible with TYPO3 8, 9 and 10. Additionally, plans are to **introduce a new TypoScript parameter `doNotHash`** to make the plugin generate specific files without hashes. That'd be helpful to include an `rte.less` file parsed into `rte.less` to the `ckeditor` YAML config file (`contentsCss`) without the file name changing due to using LESS variables.
Additionally, I'd like to **drop `oyejorge/less.php` (as it has been deprecated) and replace it with [Wikimedia's well-maintained fork](https://github.com/wikimedia/less.php**) which just released version 2.0.0 of `less.php`.
Last but not least, I'd like to make the extension Composer-ready (You still need to register it on packagist.org, but that's just a one-time task).

If you are not okay with any of these changes, please let me know, otherwise I'd be happy to be a collaborator and keeping the extension updated. ✌️

**Comment by svewap** [comment]
@oliverschloebe  Thank you very much. I added you to this rep. I will look at the pull request, test it, give feedback and make a release in the rep this weekend.

**Comment by oliverschloebe** [comment]
> @oliverschloebe Thank you very much. I added you to this rep. I will look at the pull request, test it, give feedback and make a release in the TER this weekend.

Thank you! In order to finish TYPO3 Composer integration for your extension it's worth noting that there's a [pretty handy guide](https://www.nitsan.in/de/blog/publish-and-maintain-your-ter-typo3-extensions-with-composer-git-packagist/) on how to set up the whole thing before drafting a new release.

Happy to help! ✌️
